const products = [
	{
		id: 0,
		name: "Kross",
		description: "lorem",
		category: "kross",
		price: 2999.99,
		image: "./images/kross.png",
		sale: true,
		saleAmount: 200,
	},
	{
		id: 1,
		name: "Vintage",
		description: "lorem",
		category: "vintage",
		price: 3999.99,
		image: "./images/vintage.png",
	},
	{
		id: 2,
		name: "Mountain",
		description: "lorem",
		category: "mountain",
		price: 2589.99,
		image: "./images/mountain.png",
		sale: true,
		saleAmount: 150,
	},
	{
		id: 3,
		name: "E-bike",
		description: "lorem",
		category: "e-bike",
		price: 4599.99,
		image: "./images/e-bike.png",
	},
	{
		id: 4,
		name: "Child",
		description: "lorem",
		category: "child",
		price: 859.99,
		image: "./images/child.png",
		sale: true,
		saleAmount: 300,
	},
];
